'use strict';
const $=s=>document.querySelector(s);let data={records:[],categories:[]},activityTypes=[],page=1,editing=null;const size=20,STORAGE_KEY='tabien-khum-v1';
const escapeHTML=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const CATEGORY_TYPES=[
  'กิจการที่เกี่ยวกับสัตว์เลี้ยง',
  'กิจการที่เกี่ยวกับสัตว์และผลิตภัณฑ์',
  'กิจการที่เกี่ยวกับอาหาร เครื่องดื่ม น้ำดื่ม ยกเว้นในสถานที่จำหน่ายอาหาร การเร่ขาย การขายในตลาด และการผลิตเพื่อบริโภคในครัวเรือน',
  'กิจการที่เกี่ยวกับยา เวชภัณฑ์ อุปกรณ์การแพทย์ เครื่องสำอาง และผลิตภัณฑ์ทำความสะอาด',
  'กิจการที่เกี่ยวกับการเกษตร',
  'กิจการที่เกี่ยวกับโลหะหรือแร่',
  'กิจการที่เกี่ยวกับยานยนต์ เครื่องจักรหรือเครื่องกล',
  'กิจการที่เกี่ยวกับไม้หรือกระดาษ',
  'กิจการที่เกี่ยวกับการบริการ',
  'กิจการที่เกี่ยวกับสิ่งทอ',
  'กิจการที่เกี่ยวกับหิน ดิน ทราย ซีเมนต์ หรือวัตถุที่คล้ายคลึง',
  'กิจการที่เกี่ยวกับปิโตรเลียม ปิโตรเคมี ถ่านหิน ถ่านโค้ก และสารเคมีต่าง ๆ',
  'กิจการอื่น ๆ'
];
const categoryNo=value=>Number(String(value||'').match(/หมวด\s*(\d+)/)?.[1]||0);
const categoryLabels=()=>activityTypes.length?activityTypes.map(x=>x.name):CATEGORY_TYPES;
const activityCode=value=>{const match=String(value||'').replace(/\s/g,'').match(/^(\d+)\((\d+)\)/);return match?{category:Number(match[1]),subcategory:Number(match[2])}:{category:0,subcategory:0};};
const activityGroup=number=>activityTypes.find(group=>Number(group.number)===Number(number));
const activityItem=(category,subcategory)=>activityGroup(category)?.items.find(item=>Number(item.number)===Number(subcategory));
function populateFormSubcategories(category,preserve=''){const select=$('#formSubcategory'),group=activityGroup(category);if(!group){select.innerHTML='<option value="">เลือกประเภทกิจการก่อน</option>';select.disabled=true;return;}select.disabled=false;select.innerHTML='<option value="">เลือกกิจการย่อย</option>'+group.items.map(item=>`<option value="${item.number}">${category}(${item.number}) ${escapeHTML(item.name)}</option>`).join('');select.value=String(preserve||'');}
function syncFormCode(){const main=$('#formCategory').value,sub=$('#formSubcategory').value,input=$('#form').elements.code;if(!main||!sub)return;const suffix=String(input.value||'').replace(/^\s*\d+\s*\(\s*\d+\s*\)/,'');input.value=`${main}(${sub})${suffix}`;}
function notice(message,error=false){$('#notice').textContent=message;$('#notice').className=error?'error':'';}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(data));}
function cleanRecord(record){if(!record||typeof record!=='object'||!String(record.name||'').trim())throw Error('กรุณาระบุชื่อผู้ประกอบการ');const copy={...record};delete copy.id;if(!Array.isArray(copy.history))copy.history=[];return copy;}
async function api(path,options={}){
  const method=options.method||'GET';
  if(path==='/api/records'&&method==='GET')return structuredClone(data);
  if(path==='/api/records'&&method==='POST'){const record=cleanRecord(JSON.parse(options.body));const id=Math.max(0,...data.records.map(r=>Number(r.id)||0))+1;data.records.unshift({...record,id});save();return{id};}
  const match=path.match(/^\/api\/records\/(\d+)$/);
  if(match){const id=Number(match[1]),index=data.records.findIndex(r=>Number(r.id)===id);if(index<0)throw Error('ไม่พบรายการ');if(method==='DELETE')data.records.splice(index,1);else if(method==='PUT')data.records[index]={...cleanRecord(JSON.parse(options.body)),id};else throw Error('ไม่รองรับคำสั่ง');save();return{ok:true};}
  if(path==='/api/restore'&&method==='POST'){const payload=JSON.parse(options.body);if(!Array.isArray(payload.records)||!Array.isArray(payload.categories))throw Error('ไฟล์สำรองไม่ถูกต้อง');data={records:payload.records.map((r,i)=>({...cleanRecord(r),id:Number(r.id)||i+1})),categories:payload.categories};save();return{count:data.records.length};}
  throw Error('ไม่พบเส้นทางข้อมูล');
}
async function initialize(){const types=await fetch('activity-types.json');if(!types.ok)throw Error('โหลดรายการกิจการตามเทศบัญญัติไม่สำเร็จ');activityTypes=await types.json();const stored=localStorage.getItem(STORAGE_KEY);if(stored){data=JSON.parse(stored);return;}const res=await fetch('initial.json');if(!res.ok)throw Error('โหลดข้อมูลเริ่มต้นไม่สำเร็จ');data=await res.json();data.records=data.records.map((r,i)=>({...r,id:i+1}));save();}
function updateSubcategories(preserve=''){const cat=Number($('#category').value),select=$('#subcategory'),group=activityTypes.find(x=>x.number===cat);if(!group){select.innerHTML='<option value="">ทุกกิจการย่อย</option>';select.value='';select.hidden=true;select.disabled=true;return;}select.hidden=false;select.disabled=false;select.innerHTML='<option value="">ทุกกิจการย่อยในประเภทนี้</option>'+group.items.map(item=>{const prefix=`${cat}(${item.number})`,count=data.records.filter(r=>String(r.code||'').replace(/\s/g,'').startsWith(prefix)).length;return `<option value="${item.number}">${prefix} ${escapeHTML(item.name)} (${count.toLocaleString('th-TH')} รายการ)</option>`;}).join('');select.value=preserve;}
function renderCategoryCards(){const labels=categoryLabels(),counts=Array.from({length:13},(_,i)=>data.records.filter(r=>categoryNo(r.category)===i+1).length);$('#categoryCards').innerHTML=labels.map((label,i)=>`<button type="button" class="category-card" data-category="${i+1}"><span class="category-number">${i+1}</span><span class="category-copy"><b>${escapeHTML(label)}</b><em>${counts[i].toLocaleString('th-TH')} รายการ</em></span></button>`).join('');}
async function load(){try{data=await api('/api/records');const current=$('#category').value,currentSub=$('#subcategory').value,labels=categoryLabels();const categoryOptions=labels.map((label,i)=>`<option value="${i+1}">${i+1}. ${escapeHTML(label)}</option>`).join('');$('#category').innerHTML='<option value="">ทุกประเภทกิจการ (13 ประเภท)</option>'+categoryOptions;$('#category').value=current;updateSubcategories(currentSub);$('#formCategory').innerHTML='<option value="">เลือกประเภทกิจการ</option>'+categoryOptions;const years=[...new Set([...data.records.flatMap(r=>(r.history||[]).map(h=>h.year)),String(new Date().getFullYear()+543)])].sort((a,b)=>Number(b)-Number(a));const yr=$('#year').value;$('#year').innerHTML=years.map(y=>`<option>${escapeHTML(y)}</option>`).join('');$('#year').value=yr||String(new Date().getFullYear()+543);$('#total').textContent=data.records.length.toLocaleString('th-TH');$('#catCount').textContent='13';renderCategoryCards();render();}catch(e){notice(e.message,true);}}
function filtered(){const q=$('#search').value.trim().toLowerCase(),cat=$('#category').value,sub=$('#subcategory').value,prefix=cat&&sub?`${cat}(${sub})`:'';return data.records.filter(r=>(!cat||categoryNo(r.category)===Number(cat))&&(!prefix||String(r.code||'').replace(/\s/g,'').startsWith(prefix))&&(!q||JSON.stringify(r).toLowerCase().includes(q)));}
function render(){const list=filtered(),year=$('#year').value;page=Math.max(1,Math.min(page,Math.ceil(list.length/size)||1));$('#licensed').textContent=data.records.filter(r=>(r.history||[]).some(h=>h.year===year&&h.number)).length;$('#result').textContent=`พบ ${list.length.toLocaleString('th-TH')} รายการ • ปีงบประมาณ ${year}`;$('#rows').innerHTML=list.slice((page-1)*size,page*size).map(r=>{const h=(r.history||[]).find(h=>h.year===year)||{},code=activityCode(r.code),cat=code.category||categoryNo(r.category),group=activityGroup(cat),item=activityItem(cat,code.subcategory);return `<tr><td class="activity-cell"><span class="tag">ประเภท ${cat||'—'}</span><div class="category-name">${escapeHTML(group?.name||r.category||'ไม่ระบุประเภท')}</div><small class="subcategory-name"><b>${escapeHTML(r.code||'—')}</b>${item?' '+escapeHTML(item.name):''}<br>ลำดับ ${escapeHTML(r.sequence||'—')}</small></td><td><div class="name">${escapeHTML(r.name)}</div><small>${escapeHTML(r.address)}</small></td><td>${escapeHTML(r.business)}</td><td>${r.fee?escapeHTML(Number.isFinite(Number(r.fee))?Number(r.fee).toLocaleString('th-TH'):r.fee):'—'}</td><td>${escapeHTML(h.number||'—')}<small>ต่ออายุ: ${escapeHTML(h.renewed||'—')}<br>หมดอายุ: ${escapeHTML(h.expires||'—')}</small></td><td><div class="row-actions"><button class="secondary" data-edit="${r.id}">เปิด / แก้ไข</button><button class="secondary delete" data-delete="${r.id}">ลบ</button></div></td></tr>`}).join('')||'<tr><td colspan="6" class="empty">ไม่พบรายการที่ค้นหา</td></tr>';$('#pageInfo').textContent=`หน้า ${page} / ${Math.ceil(list.length/size)||1}`;$('#prev').disabled=page===1;$('#next').disabled=page*size>=list.length;}
function historyRow(h={}){const tr=document.createElement('tr');tr.innerHTML=['year','number','renewed','expires'].map(k=>`<td><input data-key="${k}" aria-label="${escapeHTML(k)}" value="${escapeHTML(h[k]||'')}" ${k==='year'?'required pattern="[0-9]{4}"':''}></td>`).join('')+'<td><button type="button" class="secondary">ลบปี</button></td>';tr.querySelector('button').onclick=()=>tr.remove();$('#history').append(tr);}
function edit(r=null){editing=r;$('#form').reset();$('#formTitle').textContent=r?'รายละเอียด / แก้ไขทะเบียน':'เพิ่มทะเบียน';const code=activityCode(r?.code),main=code.category||categoryNo(r?.category);$('#formCategory').value=main||'';populateFormSubcategories(main,code.subcategory);for(const k of ['sequence','code','fee','name','address','business','notes'])$('#form').elements[k].value=r?.[k]||'';$('#history').innerHTML='';(r?.history||[{year:$('#year').value}]).forEach(historyRow);$('#editor').showModal();}
$('#form').onsubmit=async e=>{e.preventDefault();const fields=Object.fromEntries(new FormData(e.target)),main=Number(fields.categoryMain),sub=Number(fields.categorySub);if(!activityItem(main,sub))return alert('กรุณาเลือกประเภทกิจการและกิจการย่อยให้ครบถ้วน');const r={...editing,...fields,category:`หมวด ${main}`,code:fields.code.trim()||`${main}(${sub})`,history:[...$('#history').rows].map(tr=>Object.fromEntries([...tr.querySelectorAll('input')].map(i=>[i.dataset.key,i.value.trim()])))};delete r.categoryMain;delete r.categorySub;if(new Set(r.history.map(h=>h.year)).size!==r.history.length)return alert('ปีในประวัติใบอนุญาตซ้ำกัน กรุณาตรวจสอบ');const b=e.submitter;b.disabled=true;try{await api('/api/records'+(editing?'/'+editing.id:''),{method:editing?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(r)});$('#editor').close();notice('บันทึกข้อมูลเรียบร้อย');await load();}catch(err){notice(err.message,true);alert(err.message);}finally{b.disabled=false;}};
$('#rows').onclick=async e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.edit)edit(data.records.find(r=>r.id===Number(b.dataset.edit)));if(b.dataset.delete&&confirm('ลบทะเบียนนี้? แนะนำให้สำรองข้อมูลก่อนลบ')){try{await api('/api/records/'+b.dataset.delete,{method:'DELETE'});notice('ลบรายการแล้ว');await load();}catch(err){notice(err.message,true);}}};
$('#add').onclick=()=>edit();$('#close').onclick=()=>$('#editor').close();$('#addYear').onclick=()=>historyRow();$('#formCategory').addEventListener('change',e=>{populateFormSubcategories(e.target.value);syncFormCode();});$('#formSubcategory').addEventListener('change',syncFormCode);$('#search').addEventListener('input',()=>{page=1;render();});$('#year').addEventListener('change',()=>{page=1;render();});$('#category').addEventListener('change',()=>{page=1;updateSubcategories();render();});$('#subcategory').addEventListener('change',()=>{page=1;render();});$('#prev').onclick=()=>{page--;render();};$('#next').onclick=()=>{page++;render();};
$('#toggleCategories').onclick=()=>{const cards=$('#categoryCards'),open=cards.hidden;cards.hidden=!open;$('#toggleCategories').setAttribute('aria-expanded',String(open));$('#toggleCategories').textContent=open?'ซ่อนรายการ':'ดูทั้ง 13 ประเภท';};
$('#categoryCards').onclick=e=>{const card=e.target.closest('[data-category]');if(!card)return;$('#category').value=card.dataset.category;updateSubcategories();page=1;render();document.querySelector('.panel').scrollIntoView({behavior:'smooth',block:'start'});};
function download(text,name,type){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('#backup').onclick=()=>download(JSON.stringify(data,null,2),'ทะเบียนคุม-backup-'+new Date().toISOString().slice(0,10)+'.json','application/json');
$('#csv').onclick=()=>{const year=$('#year').value;const rows=[['หมวด','ลำดับ','รหัส','ชื่อ-สกุล','ที่อยู่','ประเภทกิจการ','ค่าธรรมเนียม','ปี','เล่ม/เลข','ต่ออายุ','หมดอายุ','หมายเหตุ'],...filtered().map(r=>{const h=(r.history||[]).find(h=>h.year===year)||{};return [r.category,r.sequence,r.code,r.name,r.address,r.business,r.fee,year,h.number,h.renewed,h.expires,r.notes];})];download('\ufeff'+rows.map(r=>r.map(v=>{let s=String(v??'');if(/^[=+@\-\t\r]/.test(s))s="'"+s;return '"'+s.replace(/"/g,'""')+'"';}).join(',')).join('\r\n'),'ทะเบียนคุม-'+year+'.csv','text/csv;charset=utf-8');};
function cellText(value){if(value==null)return'';if(value instanceof Date)return String(value.getDate()).padStart(2,'0')+'/'+String(value.getMonth()+1).padStart(2,'0')+'/'+value.getFullYear();return String(value).trim();}
function parseWorkbook(buffer){if(!window.XLSX)throw Error('ตัวอ่าน Excel โหลดไม่สำเร็จ กรุณาลองใหม่');const book=XLSX.read(buffer,{type:'array',cellDates:true});const records=[],categories=[];for(const name of book.SheetNames){const sheet=book.Sheets[name],rows=XLSX.utils.sheet_to_json(sheet,{header:1,raw:true,defval:''});if(!rows.slice(0,5).some(row=>row.some(cell=>String(cell).includes('ชื่อ-สกุล'))))continue;const category=name.trim();categories.push({name:category,source_title:cellText(rows[0]?.[0])});const yearRow=rows.slice(0,5).find(row=>row.slice(7).some(v=>Number(v)>=2500&&Number(v)<=2700))||[];const years={};yearRow.forEach((value,index)=>{if(index>=7&&Number(value)>=2500&&Number(value)<=2700)years[index]=String(Math.trunc(Number(value)));});rows.forEach((row,index)=>{if(row.length<7||cellText(row[6])!=='เล่ม/เลข'||![2,3,4].some(i=>row[i]!==''&&row[i]!=null))return;const history=Object.entries(years).map(([col,year])=>({year,number:cellText(rows[index]?.[col]),renewed:cellText(rows[index+1]?.[col]),expires:cellText(rows[index+2]?.[col])}));records.push({category,sequence:cellText(row[0]),code:cellText(row[1]),name:cellText(row[2]),address:cellText(row[3]),business:cellText(row[4]),fee:cellText(row[5]),notes:'',history,source_row:index+1});});}return{records,categories};}
const thaiNumber=value=>Number(String(value||'').replace(/[๐-๙]/g,c=>'๐๑๒๓๔๕๖๗๘๙'.indexOf(c)));
function classifyRecords(records,year){const old=records.filter(r=>(r.history||[]).some(h=>Number(h.year)<year&&String(h.number||'').trim()));const current=records.filter(r=>(r.history||[]).some(h=>Number(h.year)===year&&String(h.number||'').trim()));const cancelled=old.filter(r=>JSON.stringify(r).includes('ยกเลิก'));const renewed=current.filter(r=>(r.history||[]).some(h=>Number(h.year)<year&&String(h.number||'').trim()));return[old.length,cancelled.length,renewed.length,current.length-renewed.length];}
function summaryCounts(category,sub,year){const prefix=`${category}(${sub})`;return classifyRecords(data.records.filter(r=>String(r.code||'').replace(/\s/g,'').startsWith(prefix)),year);}
function categoryReport(year){return categoryLabels().map((label,index)=>({number:index+1,label,values:classifyRecords(data.records.filter(r=>categoryNo(r.category)===index+1),year)}));}
function renderSummary(){const year=Number($('#year').value),report=categoryReport(year),totals=[0,0,0,0];$('#reportTitle').textContent=`สรุปกิจการที่เป็นอันตรายต่อสุขภาพ ปี ${year}`;$('#reportRows').innerHTML=report.map(row=>{row.values.forEach((v,i)=>totals[i]+=v);return `<tr><td><b>${row.number}.</b> ${escapeHTML(row.label)}</td>${row.values.map(v=>`<td>${v.toLocaleString('th-TH')}</td>`).join('')}</tr>`;}).join('');['Old','Cancelled','Renewed','New'].forEach((name,i)=>{$('#report'+name).textContent=totals[i].toLocaleString('th-TH');$('#reportTotal'+name).textContent=totals[i].toLocaleString('th-TH');});return{year,report,totals};}
async function downloadSummary(){const button=$('#downloadReport'),year=Number($('#year').value);button.disabled=true;notice('กำลังจัดทำ Excel พร้อมตาราง…');try{if(!window.ExcelJS)throw Error('ตัวสร้างเอกสาร Excel โหลดไม่สำเร็จ');const response=await fetch('summary-template.xlsx');if(!response.ok)throw Error('โหลดแม่แบบเอกสารไม่สำเร็จ');const workbook=new ExcelJS.Workbook();await workbook.xlsx.load(await response.arrayBuffer());const sheet=workbook.worksheets[0];sheet.getCell(1,1).value=`ข้อมูลการต่อใบอนุญาตกิจการที่เป็นอันตรายต่อสุขภาพ ประจำปี ${year} ( 1 ต.ค. ${year-1} - 30 ก.ย. ${year} )`;let category=0;for(let row=5;row<=sheet.rowCount;row++){const a=String(sheet.getCell(row,1).text||'').trim(),heading=a.match(/^(\d{1,2})\s*\.\s*กิจการ/);if(heading){category=Number(heading[1]);continue;}if(category===1&&/^\(1\)\s*การฆ่า/.test(a))category=2;const sub=a.match(/^[（(]\s*([0-9๐-๙]+)\s*[）)]/)||a.match(/^([0-9๐-๙]+)\s*\./),numeric=[5,6,7,8].some(col=>typeof sheet.getCell(row,col).value==='number');if(!sub&&!numeric)continue;for(let col=5;col<=8;col++)sheet.getCell(row,col).value=0;if(!sub||!category)continue;summaryCounts(category,thaiNumber(sub[1]),year).forEach((value,index)=>sheet.getCell(row,5+index).value=value);}workbook.calcProperties.fullCalcOnLoad=true;const output=await workbook.xlsx.writeBuffer();download(output,`สรุปกิจการอันตราย-ปี-${year}.xlsx`,'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');notice(`ดาวน์โหลด Excel ปี ${year} พร้อมรูปแบบตารางแล้ว`);}catch(error){notice(error.message,true);}finally{button.disabled=false;}}
function printSummary(){const{year,report,totals}=renderSummary(),popup=window.open('','_blank');if(!popup)return notice('เบราว์เซอร์ปิดกั้นหน้าต่างพิมพ์ กรุณาอนุญาตป๊อปอัป',true);const rows=report.map(row=>`<tr><td>${row.number}. ${escapeHTML(row.label)}</td>${row.values.map(v=>`<td>${v}</td>`).join('')}</tr>`).join('');popup.document.write(`<!doctype html><html lang="th"><head><meta charset="utf-8"><title>รายงานปี ${year}</title><style>body{font-family:Tahoma,sans-serif;padding:24px;color:#123}h1{text-align:center;font-size:20px}p{text-align:center}table{width:100%;border-collapse:collapse;font-size:11px}th,td{border:1px solid #333;padding:7px}th{background:#dcebe5}td:not(:first-child),th:not(:first-child){text-align:center}tfoot{font-weight:bold}@page{size:A4 landscape;margin:12mm}</style></head><body><h1>ข้อมูลการต่อใบอนุญาตกิจการที่เป็นอันตรายต่อสุขภาพ</h1><p>ประจำปี ${year} (1 ต.ค. ${year-1} - 30 ก.ย. ${year})</p><table><thead><tr><th>ประเภทกิจการ</th><th>รายเก่า</th><th>ยกเลิก</th><th>รายต่อ</th><th>รายใหม่</th></tr></thead><tbody>${rows}</tbody><tfoot><tr><td>รวมทั้งหมด</td>${totals.map(v=>`<td>${v}</td>`).join('')}</tr></tfoot></table><script>onload=()=>{print();onafterprint=()=>close()}<\/script></body></html>`);popup.document.close();}
$('#summaryXlsx').onclick=()=>{renderSummary();$('#reportDialog').showModal();};$('#closeReport').onclick=()=>$('#reportDialog').close();$('#downloadReport').onclick=downloadSummary;$('#printReport').onclick=printSummary;
$('#import').onclick=()=>$('#excelFile').click();$('#excelFile').onchange=async e=>{const f=e.target.files[0];if(!f)return;if(!confirm('นำเข้าแบบเพิ่มรายการ ไม่ทับข้อมูลเดิม หากนำเข้าไฟล์เดิมซ้ำจะมีรายการซ้ำ ต้องการดำเนินการหรือไม่?')){e.target.value='';return;}notice('กำลังนำเข้า Excel…');try{const parsed=parseWorkbook(await f.arrayBuffer());if(!parsed.records.length)throw Error('ไม่พบข้อมูลทะเบียนใน Excel');const next=Math.max(0,...data.records.map(r=>Number(r.id)||0))+1;data.records.unshift(...parsed.records.map((r,i)=>({...r,id:next+i})));const names=new Set(data.categories.map(c=>c.name));data.categories.push(...parsed.categories.filter(c=>!names.has(c.name)));save();await load();notice(`นำเข้าเรียบร้อย ${parsed.records.length} รายการ`);}catch(err){notice(err.message,true);}e.target.value='';};
$('#restore').onclick=()=>$('#jsonFile').click();$('#jsonFile').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const payload=JSON.parse(await f.text());if(!Array.isArray(payload.records)||!Array.isArray(payload.categories))throw Error('ไฟล์สำรองไม่ถูกต้อง');if(confirm(`กู้คืน ${payload.records.length} รายการและแทนที่ข้อมูลปัจจุบันทั้งหมด?`)){await api('/api/restore',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});await load();notice('กู้คืนข้อมูลเรียบร้อย');}}catch(err){notice(err.message,true);}e.target.value='';};initialize().then(load).catch(e=>notice(e.message,true));
