'use strict';
const $=s=>document.querySelector(s);let data={records:[],categories:[]},page=1,editing=null;const size=20,STORAGE_KEY='tabien-khum-v1';
const escapeHTML=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function notice(message,error=false){$('#notice').textContent=message;$('#notice').className=error?'error':'';}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(data));}
function cleanRecord(record){if(!record||typeof record!=='object'||!String(record.name||'').trim())throw Error('กรุณาระบุชื่อผู้ประกอบการ');const copy={...record};delete copy.id;if(!Array.isArray(copy.history))copy.history=[];return copy;}
async function api(path,options={}){
  const method=options.method||'GET';
  if(path==='/api/records'&&method==='GET')return structuredClone(data);
  if(path==='/api/records'&&method==='POST'){const record=cleanRecord(JSON.parse(options.body));const id=Math.max(0,...data.records.map(r=>Number(r.id)||0))+1;data.records.unshift({...record,id});save();return{id};}
  const match=path.match(/^\/api\/records\/(\d+)$/);
  if(match){const id=Number(match[1]),index=data.records.findIndex(r=>Number(r.id)===id);if(index<0)throw Error('ไม่พบรายการ');if(method==='DELETE')data.records.splice(index,1);else if(method==='PUT')data.records[index]={...cleanRecord(JSON.parse(options.body)),id};else throw Error('ไม่รองรับคำสั่ง');save();return{ok:true};}
  if(path==='/api/restore'&&method==='POST'){const payload=JSON.parse(options.body);if(!Array.isArray(payload.records)||!Array.isArray(payload.categories))throw Error('ไฟล์สำรองไม่ถูกต้อง');data={records:payload.records.map((r,i)=>({...cleanRecord(r),id:Number(r.id)||i+1})),categories:payload.categories};save();return{count:data.records.length};}
  throw Error('ไม่พบเส้นทางข้อมูล');
}
async function initialize(){const stored=localStorage.getItem(STORAGE_KEY);if(stored){data=JSON.parse(stored);return;}const res=await fetch('initial.json');if(!res.ok)throw Error('โหลดข้อมูลเริ่มต้นไม่สำเร็จ');data=await res.json();data.records=data.records.map((r,i)=>({...r,id:i+1}));save();}
async function load(){try{data=await api('/api/records');const current=$('#category').value;const cats=[...new Set([...data.categories.map(c=>c.name),...data.records.map(r=>r.category)])];$('#category').innerHTML='<option value="">ทุกหมวดกิจการ</option>'+cats.map(c=>`<option>${escapeHTML(c)}</option>`).join('');$('#category').value=current;$('#categories').innerHTML=cats.map(c=>`<option value="${escapeHTML(c)}">`).join('');const years=[...new Set([...data.records.flatMap(r=>(r.history||[]).map(h=>h.year)),String(new Date().getFullYear()+543)])].sort((a,b)=>Number(b)-Number(a));const yr=$('#year').value;$('#year').innerHTML=years.map(y=>`<option>${escapeHTML(y)}</option>`).join('');$('#year').value=yr||String(new Date().getFullYear()+543);$('#total').textContent=data.records.length.toLocaleString('th-TH');$('#catCount').textContent=cats.length;render();}catch(e){notice(e.message,true);}}
function filtered(){const q=$('#search').value.trim().toLowerCase(),cat=$('#category').value;return data.records.filter(r=>(!cat||r.category===cat)&&(!q||JSON.stringify(r).toLowerCase().includes(q)));}
function render(){const list=filtered(),year=$('#year').value;page=Math.max(1,Math.min(page,Math.ceil(list.length/size)||1));$('#licensed').textContent=data.records.filter(r=>(r.history||[]).some(h=>h.year===year&&h.number)).length;$('#result').textContent=`พบ ${list.length.toLocaleString('th-TH')} รายการ • ปีงบประมาณ ${year}`;$('#rows').innerHTML=list.slice((page-1)*size,page*size).map(r=>{const h=(r.history||[]).find(h=>h.year===year)||{};return `<tr><td><span class="tag">${escapeHTML(r.category)}</span><small>ลำดับ ${escapeHTML(r.sequence||'—')} · ${escapeHTML(r.code||'—')}</small></td><td><div class="name">${escapeHTML(r.name)}</div><small>${escapeHTML(r.address)}</small></td><td>${escapeHTML(r.business)}</td><td>${r.fee?escapeHTML(Number.isFinite(Number(r.fee))?Number(r.fee).toLocaleString('th-TH'):r.fee):'—'}</td><td>${escapeHTML(h.number||'—')}<small>ต่ออายุ: ${escapeHTML(h.renewed||'—')}<br>หมดอายุ: ${escapeHTML(h.expires||'—')}</small></td><td><div class="row-actions"><button class="secondary" data-edit="${r.id}">เปิด / แก้ไข</button><button class="secondary delete" data-delete="${r.id}">ลบ</button></div></td></tr>`}).join('')||'<tr><td colspan="6" class="empty">ไม่พบรายการที่ค้นหา</td></tr>';$('#pageInfo').textContent=`หน้า ${page} / ${Math.ceil(list.length/size)||1}`;$('#prev').disabled=page===1;$('#next').disabled=page*size>=list.length;}
function historyRow(h={}){const tr=document.createElement('tr');tr.innerHTML=['year','number','renewed','expires'].map(k=>`<td><input data-key="${k}" aria-label="${escapeHTML(k)}" value="${escapeHTML(h[k]||'')}" ${k==='year'?'required pattern="[0-9]{4}"':''}></td>`).join('')+'<td><button type="button" class="secondary">ลบปี</button></td>';tr.querySelector('button').onclick=()=>tr.remove();$('#history').append(tr);}
function edit(r=null){editing=r;$('#form').reset();$('#formTitle').textContent=r?'รายละเอียด / แก้ไขทะเบียน':'เพิ่มทะเบียน';for(const k of ['category','sequence','code','fee','name','address','business','notes'])$('#form').elements[k].value=r?.[k]||'';$('#history').innerHTML='';(r?.history||[{year:$('#year').value}]).forEach(historyRow);$('#editor').showModal();}
$('#form').onsubmit=async e=>{e.preventDefault();const r={...editing,...Object.fromEntries(new FormData(e.target)),history:[...$('#history').rows].map(tr=>Object.fromEntries([...tr.querySelectorAll('input')].map(i=>[i.dataset.key,i.value.trim()])))};if(new Set(r.history.map(h=>h.year)).size!==r.history.length)return alert('ปีในประวัติใบอนุญาตซ้ำกัน กรุณาตรวจสอบ');const b=e.submitter;b.disabled=true;try{await api('/api/records'+(editing?'/'+editing.id:''),{method:editing?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(r)});$('#editor').close();notice('บันทึกข้อมูลเรียบร้อย');await load();}catch(err){notice(err.message,true);alert(err.message);}finally{b.disabled=false;}};
$('#rows').onclick=async e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.edit)edit(data.records.find(r=>r.id===Number(b.dataset.edit)));if(b.dataset.delete&&confirm('ลบทะเบียนนี้? แนะนำให้สำรองข้อมูลก่อนลบ')){try{await api('/api/records/'+b.dataset.delete,{method:'DELETE'});notice('ลบรายการแล้ว');await load();}catch(err){notice(err.message,true);}}};
$('#add').onclick=()=>edit();$('#close').onclick=()=>$('#editor').close();$('#addYear').onclick=()=>historyRow();for(const id of ['search','category','year'])$('#'+id).addEventListener(id==='search'?'input':'change',()=>{page=1;render();});$('#prev').onclick=()=>{page--;render();};$('#next').onclick=()=>{page++;render();};
function download(text,name,type){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('#backup').onclick=()=>download(JSON.stringify(data,null,2),'ทะเบียนคุม-backup-'+new Date().toISOString().slice(0,10)+'.json','application/json');
$('#csv').onclick=()=>{const year=$('#year').value;const rows=[['หมวด','ลำดับ','รหัส','ชื่อ-สกุล','ที่อยู่','ประเภทกิจการ','ค่าธรรมเนียม','ปี','เล่ม/เลข','ต่ออายุ','หมดอายุ','หมายเหตุ'],...filtered().map(r=>{const h=(r.history||[]).find(h=>h.year===year)||{};return [r.category,r.sequence,r.code,r.name,r.address,r.business,r.fee,year,h.number,h.renewed,h.expires,r.notes];})];download('\ufeff'+rows.map(r=>r.map(v=>{let s=String(v??'');if(/^[=+@\-\t\r]/.test(s))s="'"+s;return '"'+s.replace(/"/g,'""')+'"';}).join(',')).join('\r\n'),'ทะเบียนคุม-'+year+'.csv','text/csv;charset=utf-8');};
function cellText(value){if(value==null)return'';if(value instanceof Date)return String(value.getDate()).padStart(2,'0')+'/'+String(value.getMonth()+1).padStart(2,'0')+'/'+value.getFullYear();return String(value).trim();}
function parseWorkbook(buffer){if(!window.XLSX)throw Error('ตัวอ่าน Excel โหลดไม่สำเร็จ กรุณาลองใหม่');const book=XLSX.read(buffer,{type:'array',cellDates:true});const records=[],categories=[];for(const name of book.SheetNames){const sheet=book.Sheets[name],rows=XLSX.utils.sheet_to_json(sheet,{header:1,raw:true,defval:''});if(!rows.slice(0,5).some(row=>row.some(cell=>String(cell).includes('ชื่อ-สกุล'))))continue;const category=name.trim();categories.push({name:category,source_title:cellText(rows[0]?.[0])});const yearRow=rows.slice(0,5).find(row=>row.slice(7).some(v=>Number(v)>=2500&&Number(v)<=2700))||[];const years={};yearRow.forEach((value,index)=>{if(index>=7&&Number(value)>=2500&&Number(value)<=2700)years[index]=String(Math.trunc(Number(value)));});rows.forEach((row,index)=>{if(row.length<7||cellText(row[6])!=='เล่ม/เลข'||![2,3,4].some(i=>row[i]!==''&&row[i]!=null))return;const history=Object.entries(years).map(([col,year])=>({year,number:cellText(rows[index]?.[col]),renewed:cellText(rows[index+1]?.[col]),expires:cellText(rows[index+2]?.[col])}));records.push({category,sequence:cellText(row[0]),code:cellText(row[1]),name:cellText(row[2]),address:cellText(row[3]),business:cellText(row[4]),fee:cellText(row[5]),notes:'',history,source_row:index+1});});}return{records,categories};}
$('#import').onclick=()=>$('#excelFile').click();$('#excelFile').onchange=async e=>{const f=e.target.files[0];if(!f)return;if(!confirm('นำเข้าแบบเพิ่มรายการ ไม่ทับข้อมูลเดิม หากนำเข้าไฟล์เดิมซ้ำจะมีรายการซ้ำ ต้องการดำเนินการหรือไม่?')){e.target.value='';return;}notice('กำลังนำเข้า Excel…');try{const parsed=parseWorkbook(await f.arrayBuffer());if(!parsed.records.length)throw Error('ไม่พบข้อมูลทะเบียนใน Excel');const next=Math.max(0,...data.records.map(r=>Number(r.id)||0))+1;data.records.unshift(...parsed.records.map((r,i)=>({...r,id:next+i})));const names=new Set(data.categories.map(c=>c.name));data.categories.push(...parsed.categories.filter(c=>!names.has(c.name)));save();await load();notice(`นำเข้าเรียบร้อย ${parsed.records.length} รายการ`);}catch(err){notice(err.message,true);}e.target.value='';};
$('#restore').onclick=()=>$('#jsonFile').click();$('#jsonFile').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const payload=JSON.parse(await f.text());if(!Array.isArray(payload.records)||!Array.isArray(payload.categories))throw Error('ไฟล์สำรองไม่ถูกต้อง');if(confirm(`กู้คืน ${payload.records.length} รายการและแทนที่ข้อมูลปัจจุบันทั้งหมด?`)){await api('/api/restore',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});await load();notice('กู้คืนข้อมูลเรียบร้อย');}}catch(err){notice(err.message,true);}e.target.value='';};initialize().then(load).catch(e=>notice(e.message,true));
