'use strict';
const $=selector=>document.querySelector(selector);
const STORAGE_KEY='tabien-khum-v1',MAPS_KEY='tabien-khum-google-maps-key',AUTORUN_KEY='tabien-khum-google-geocode-v1',CENTER={lat:13.9166,lng:100.4240};
const BOUNDS={north:14.035,south:13.825,east:100.555,west:100.300};
let data={records:[],categories:[]},map=null,geocoder=null,selected=null,pinMode=false,geocoding=false;
const markers=new Map();
const escapeHTML=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const hasPin=record=>Boolean(record.latitude&&record.longitude&&Number.isFinite(Number(record.latitude))&&Number.isFinite(Number(record.longitude)));
const notice=(message,error=false)=>{$('#notice').textContent=message;$('#notice').className=error?'error':'';};
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(data));}
async function loadData(){const stored=localStorage.getItem(STORAGE_KEY);if(stored){data=JSON.parse(stored);}else{const response=await fetch('initial.json');data=await response.json();localStorage.setItem(STORAGE_KEY,JSON.stringify(data));}renderList();updateStats();}
function updateStats(){const pinned=data.records.filter(hasPin).length;$('#totalCount').textContent=data.records.length.toLocaleString('en-US');$('#pinnedCount').textContent=pinned.toLocaleString('en-US');$('#unplacedCount').textContent=(data.records.length-pinned).toLocaleString('en-US');}
function renderList(){const query=$('#search').value.trim().toLowerCase(),filter=$('#pinFilter').value;const records=data.records.filter(record=>(filter==='all'||(filter==='pinned'&&hasPin(record))||(filter==='missing'&&!hasPin(record)))&&(!query||JSON.stringify([record.name,record.address,record.code,record.business]).toLowerCase().includes(query)));$('#businessList').innerHTML=records.map(record=>`<button class="business-card ${selected?.id===record.id?'active':''}" data-id="${record.id}"><span class="pin-status ${hasPin(record)?'':'missing'}">${hasPin(record)?'มีหมุด':'รอปักหมุด'}</span><b>${escapeHTML(record.name||'ไม่ระบุชื่อ')}</b><span>${escapeHTML(record.address||'ไม่ระบุที่อยู่')}</span><small>${escapeHTML(record.code||'—')} • ${escapeHTML(record.business||'')}</small></button>`).join('')||'<p style="padding:20px;color:#71847e">ไม่พบกิจการ</p>';}
function loadGoogleMaps(key){return new Promise((resolve,reject)=>{if(window.google?.maps)return resolve();window.__initRegistryGoogleMap=resolve;window.gm_authFailure=()=>{$('#apiSetup').hidden=false;notice('Google Maps API Key ไม่ถูกต้อง หรือยังไม่ได้เปิด Billing และ API ที่จำเป็น',true);reject(Error('Google Maps ยืนยัน API Key ไม่สำเร็จ'));};const script=document.createElement('script');script.src=`https://maps.googleapis.com/maps/api/js?key=${encodeURIComponent(key)}&callback=__initRegistryGoogleMap&v=weekly`;script.async=true;script.onerror=()=>reject(Error('โหลด Google Maps ไม่สำเร็จ กรุณาตรวจสอบ API Key และอินเทอร์เน็ต'));document.head.append(script);setTimeout(()=>reject(Error('Google Maps ใช้เวลาตอบสนองนานเกินไป กรุณาตรวจสอบ API Key')),20000);});}
async function connectMap(key){if(!key)return;$('#apiSetup').hidden=true;try{await loadGoogleMaps(key);map=new google.maps.Map($('#googleMap'),{center:CENTER,zoom:13,mapTypeControl:true,streetViewControl:true,fullscreenControl:true});geocoder=new google.maps.Geocoder();map.addListener('click',event=>{if(pinMode&&selected)setPin(selected,event.latLng.lat(),event.latLng.lng(),true);});renderMarkers();const requested=Number(new URLSearchParams(location.search).get('id'));if(requested){const record=data.records.find(item=>Number(item.id)===requested);if(record)selectRecord(record);}if(!localStorage.getItem(AUTORUN_KEY)&&data.records.some(record=>!hasPin(record)))setTimeout(()=>autoGeocode(true),900);}catch(error){$('#apiSetup').hidden=false;notice(error.message,true);}}
function markerFor(record){if(!hasPin(record)||!map)return null;const marker=new google.maps.Marker({map,position:{lat:Number(record.latitude),lng:Number(record.longitude)},title:record.name||'กิจการ',draggable:true});const info=new google.maps.InfoWindow({content:`<b>${escapeHTML(record.name||'ไม่ระบุชื่อ')}</b><br>${escapeHTML(record.address||'')}<br>${escapeHTML(record.code||'')}`});marker.addListener('click',()=>{selectRecord(record);info.open({map,anchor:marker});});marker.addListener('dragend',event=>setPin(record,event.latLng.lat(),event.latLng.lng(),false));markers.set(Number(record.id),marker);return marker;}
function renderMarkers(){markers.forEach(marker=>marker.setMap(null));markers.clear();data.records.forEach(markerFor);updateStats();}
function selectRecord(record){selected=record;renderList();$('#selection').hidden=false;$('#selectedName').textContent=record.name||'ไม่ระบุชื่อ';$('#selectedAddress').textContent=record.address||'ไม่ระบุที่อยู่';$('#deletePin').disabled=!hasPin(record);if(hasPin(record)){map?.panTo({lat:Number(record.latitude),lng:Number(record.longitude)});map?.setZoom(17);markers.get(Number(record.id))?.setAnimation(google.maps.Animation.BOUNCE);setTimeout(()=>markers.get(Number(record.id))?.setAnimation(null),700);}}
function setPin(record,latitude,longitude,focus=true){record.latitude=Number(latitude).toFixed(6);record.longitude=Number(longitude).toFixed(6);record.mapSource='manual';save();const old=markers.get(Number(record.id));if(old)old.setMap(null);markerFor(record);pinMode=false;document.body.classList.remove('pin-mode');updateStats();renderList();$('#deletePin').disabled=false;notice(`บันทึกหมุดของ ${record.name||'กิจการ'} แล้ว`);if(focus)map.setZoom(17);}
function deletePin(){if(!selected||!hasPin(selected)||!confirm(`ลบหมุดของ ${selected.name||'กิจการ'}?`))return;delete selected.latitude;delete selected.longitude;delete selected.mapSource;const marker=markers.get(Number(selected.id));if(marker)marker.setMap(null);markers.delete(Number(selected.id));save();updateStats();renderList();$('#deletePin').disabled=true;notice('ลบหมุดเรียบร้อย');}
function locationInsideMunicipality(location){const lat=location.lat(),lng=location.lng();return lat>=BOUNDS.south&&lat<=BOUNDS.north&&lng>=BOUNDS.west&&lng<=BOUNDS.east;}
function geocodeAddress(record){if(!String(record.address||'').trim())return Promise.resolve({results:[],status:'ZERO_RESULTS'});const address=[record.address,record.business,'เทศบาลนครบางบัวทอง','นนทบุรี','ประเทศไทย'].filter(Boolean).join(' ');return new Promise(resolve=>geocoder.geocode({address,componentRestrictions:{country:'TH'},bounds:new google.maps.LatLngBounds({lat:BOUNDS.south,lng:BOUNDS.west},{lat:BOUNDS.north,lng:BOUNDS.east})},(results,status)=>resolve({results,status})));}
const wait=milliseconds=>new Promise(resolve=>setTimeout(resolve,milliseconds));
async function autoGeocode(automatic=false){if(!map||!geocoder)return notice('กรุณาเชื่อมต่อ Google Maps ก่อน',true);if(geocoding)return;const queue=data.records.filter(record=>!hasPin(record));if(!queue.length){localStorage.setItem(AUTORUN_KEY,new Date().toISOString());return notice('ทุกกิจการมีหมุดแล้ว');}if(!automatic&&!confirm(`ค้นหาพิกัดอัตโนมัติ ${queue.length.toLocaleString('en-US')} กิจการจากที่อยู่ในทะเบียน? กระบวนการอาจใช้เวลาหลายนาที`))return;geocoding=true;$('#autoGeocode').disabled=true;$('#progress').hidden=false;notice(`เริ่มปักหมุดอัตโนมัติ ${queue.length.toLocaleString('en-US')} กิจการ กรุณาเปิดหน้านี้ค้างไว้`);let success=0,unresolved=0;
  for(let index=0;index<queue.length;index++){const record=queue[index];$('#progressText').textContent=`กำลังค้นหา ${record.name||'กิจการ'} (${index+1}/${queue.length})`;$('#progressNumber').textContent=`${Math.round(index/queue.length*100)}%`;$('#progressBar').value=index/queue.length*100;let response=await geocodeAddress(record);if(response.status==='OVER_QUERY_LIMIT'){await wait(1500);response=await geocodeAddress(record);}const result=response.results?.find(item=>locationInsideMunicipality(item.geometry.location));if(response.status==='OK'&&result){record.latitude=result.geometry.location.lat().toFixed(6);record.longitude=result.geometry.location.lng().toFixed(6);record.mapSource='google-geocoding';record.formattedAddress=result.formatted_address;success++;markerFor(record);}else unresolved++;if(index%10===0)save();await wait(250);}
  save();localStorage.setItem(AUTORUN_KEY,JSON.stringify({finishedAt:new Date().toISOString(),success,unresolved,total:queue.length}));geocoding=false;$('#autoGeocode').disabled=false;$('#progressBar').value=100;$('#progressNumber').textContent='100%';$('#progressText').textContent=`สำเร็จ ${success.toLocaleString('en-US')} รายการ • ต้องตรวจสอบเอง ${unresolved.toLocaleString('en-US')} รายการ`;updateStats();renderList();fitAll();notice(`ปักหมุดอัตโนมัติแล้ว ${success.toLocaleString('en-US')} กิจการ รายการที่หาไม่พบจะคงอยู่ในหมวดรอปักหมุด`);
}
function fitAll(){const bounds=new google.maps.LatLngBounds();let count=0;data.records.filter(hasPin).forEach(record=>{bounds.extend({lat:Number(record.latitude),lng:Number(record.longitude)});count++;});if(count)map.fitBounds(bounds,55);else map.setCenter(CENTER);}
function saveKey(value){const key=value.trim();if(!key)return notice('กรุณาใส่ Google Maps API Key',true);localStorage.setItem(MAPS_KEY,key);location.reload();}
$('#businessList').onclick=event=>{const card=event.target.closest('[data-id]');if(card)selectRecord(data.records.find(record=>Number(record.id)===Number(card.dataset.id)));};
$('#search').oninput=renderList;$('#pinFilter').onchange=renderList;$('#autoGeocode').onclick=()=>autoGeocode(false);$('#fitAll').onclick=()=>map?fitAll():notice('กรุณาเชื่อมต่อ Google Maps ก่อน',true);$('#addPin').onclick=()=>{if(!map)return;pinMode=true;notice(`คลิกตำแหน่งของ ${selected.name||'กิจการ'} บน Google Maps`);};$('#deletePin').onclick=deletePin;$('#currentLocation').onclick=()=>navigator.geolocation?navigator.geolocation.getCurrentPosition(position=>setPin(selected,position.coords.latitude,position.coords.longitude),()=>notice('ไม่สามารถอ่านตำแหน่งปัจจุบันได้',true)):notice('อุปกรณ์ไม่รองรับตำแหน่งปัจจุบัน',true);$('#saveApiKey').onclick=()=>saveKey($('#apiKey').value);$('#mapSettings').onclick=()=>{$('#settingsApiKey').value=localStorage.getItem(MAPS_KEY)||'';$('#settingsDialog').showModal();};$('#updateApiKey').onclick=()=>saveKey($('#settingsApiKey').value);$('#removeApiKey').onclick=()=>{if(confirm('ลบ Google Maps API Key จากเครื่องนี้?')){localStorage.removeItem(MAPS_KEY);localStorage.removeItem(AUTORUN_KEY);location.reload();}};
loadData().then(()=>{const key=localStorage.getItem(MAPS_KEY);if(key)connectMap(key);}).catch(error=>notice(error.message,true));
